---
title: "Cat food scripts final"
author: "Tina Yu"
date: "2024-06-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(tidyverse)
library(tools)
library(reshape2)
library(ggpubr)
library(broom)
library(multcompView)
library(EnvStats)
install_github("jokergoo/ComplexHeatmap")

if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("ComplexHeatmap") 
library(ComplexHeatmap)
library(circlize)
library(purrr)
library(grateful)
library(grid)
library(Polychrome)
library(ggsignif)
```

## Normality

```{r 1}
file <- read.csv("092523_master clean cat food data compiled.csv")

cultured_bacteria <- file %>%
  select(Short.ID.with.zeros, Short.ID.without.zeros, Food.texture, Raw.or.Conventional, cultured.bacteria.binary, Category) %>%
  na.omit()

shapiro.test(cultured_bacteria$cultured.bacteria.binary)

p <- ggplot(data = cultured_bacteria, aes(x = cultured.bacteria)) +
  geom_histogram(bins = 30, color = "black", fill = "lightblue") +
  theme_minimal() +
  labs(title = "Distribution of Cultured Bacteria",
       x = "# of Cultured Bacteria", y = "Count")

p

ggsave("cultured bacteria distribution.png", plot = p, width = 6, height = 4, dpi = 300)

AMR <- file %>%
  select(Short.ID.with.zeros, Short.ID.without.zeros, Raw.or.Conventional, AMRgenes..10) %>%
  na.omit()

normality <- ggplot(AMR, aes(x = AMRgenes..10)) +
  geom_histogram(bins = 30, color = "black", fill = "lightblue") +
  theme_minimal() +
  labs(title = "Distribution of AMR Genes",
       x = "# of AMR Genes", y = "Count")

normality

shapiro.test(AMR$AMRgenes..10)

ggsave("AMR distribution.png", plot = normality, width = 6, height = 4, dpi = 300)

```

## Wilcoxon rank-sum test

```{r 2}
#cultured bacteria
group_raw <- cultured_bacteria %>% 
  filter(Raw.or.Conventional == 1) %>% 
  pull(cultured.bacteria)

group_conventional <- cultured_bacteria %>% 
  filter(Raw.or.Conventional == 0) %>% 
  pull(cultured.bacteria)

grouped_data <- tibble(Raw.or.Conventional = 
                         c(rep("Raw", length(group_raw)),
                           rep("Conventional", length(group_conventional))),
                       cultured.bacteria = c(group_raw, group_conventional))

#filter(cultured.bacteria != 0) -- filtering out 0s

#side-by-side
side_by_side <- ggplot(grouped_data, 
                       aes(x = cultured.bacteria, fill = Raw.or.Conventional)) +
  geom_histogram(position = "dodge", binwidth = 0.5, alpha = 0.7) +
  labs(y = "Count", x = "# of Cultured Bacteria in Sample", fill = "Type") +
  scale_fill_manual(values = c("Raw" = "#FF8E00", "Conventional" = "#003F7D")) +
  theme_bw()

ggsave("Cultured_bacteria.png", plot = side_by_side, width = 6, height = 4, dpi = 300)

#if non-parametric
wilcox_test_result <- wilcox.test(group_raw, group_conventional)
print(wilcox_test_result)

#chi-square
test <- table(cultured_bacteria$Raw.or.Conventional, cultured_bacteria$cultured.bacteria.binary)
test

result <- chisq.test(test)
result

chisq.test(test)$expected

protein <- table(cultured_bacteria$Category, cultured_bacteria$cultured.bacteria.binary)
protein

chisq.test(protein)

texture <- table(cultured_bacteria$Food.texture, cultured_bacteria$cultured.bacteria.binary)
texture

chisq.test(texture)

```

## AMR

```{r 4}
group_raw_AMR <- AMR %>% 
  filter(Raw.or.Conventional == 1) %>% 
  pull(AMRgenes..10)

median(group_raw_AMR)

group_conventional_AMR <- AMR %>% 
  filter(Raw.or.Conventional == 0) %>% 
  pull(AMRgenes..10)

median(group_conventional_AMR)

AMR_wilcox_test_result <- wilcox.test(group_raw_AMR, group_conventional_AMR)
print(AMR_wilcox_test_result)

```

## Two-way ANOVA

```{r 5, warning = FALSE, message=FALSE}
anv <- file %>%
  select(Short.ID.with.zeros, Short.ID.without.zeros, Food.texture,
         Raw.or.Conventional, 
         Prim.protein.Detected, Category, AMRgenes..10) %>%
  na.omit()

anv1 = lm(AMRgenes..10 ~ Category, data = anv)
anova(anv1)

anv2 = lm(cultured.bacteria ~ Category*Raw.or.Conventional, data=anv)
hist(resid(anv2))
plot(predict(anv2), resid(anv2))
summary(anv2)
anova(anv2)

anv3 = lm(AMRgenes..10 ~ Category*Raw.or.Conventional, data=anv)
hist(resid(anv3))
plot(predict(anv3), resid(anv3))
summary(anv3)
anova(anv3)

anv$Category <- as.factor(anv$Category)
anv$Raw.or.Conventional <- as.factor(anv$Raw.or.Conventional)

anv3.aov <- aov(AMRgenes..10 ~ Category * Raw.or.Conventional, data=anv)
tukey.result <- TukeyHSD(anv3.aov, which = 'Category:Raw.or.Conventional')
print(tukey.result)

anv4 = lm(AMRgenes..10 ~ Food.texture * Raw.or.Conventional, data = anv)
hist(resid(anv4))
plot(predict(anv4), resid(anv4))
summary(anv4)
anova(anv4)

```

##Alpha and beta diversity

```{r 9}
diversity <- file %>%
  select(Short.ID.with.zeros, Short.ID.without.zeros, Food.texture,
         Raw.or.Conventional, Category, alphaDiv_bact_pielou, alphaDiv_bact_Faith_PD, betaDiv_bact)

alpha_Faith <- diversity %>%
  select(Short.ID.with.zeros, Short.ID.without.zeros, Food.texture,
         Raw.or.Conventional, Category, alphaDiv_bact_Faith_PD) %>%
  na.omit()

alpha_pielou <- diversity %>%
  select(Short.ID.with.zeros, Short.ID.without.zeros, Food.texture,
         Raw.or.Conventional, Category, alphaDiv_bact_pielou) %>%
  na.omit()

beta <- diversity %>%
  select(Short.ID.with.zeros, Short.ID.without.zeros, Food.texture,
         Raw.or.Conventional, Category, betaDiv_bact) %>%
  na.omit()

ggplot(alpha_Faith, aes(x = Category, y = alphaDiv_bact_Faith_PD, fill = Category)) +
  geom_boxplot()

anv5 = lm(alphaDiv_bact_Faith_PD ~ Category*Raw.or.Conventional, data=alpha_Faith)
hist(resid(anv5))
plot(predict(anv5), resid(anv5))
summary(anv5)
anova(anv5)

anv6 = lm(betaDiv_bact ~ Category*Raw.or.Conventional, data=beta)
hist(resid(anv6))
plot(predict(anv6), resid(anv6))
summary(anv6)
anova(anv6)

anv7 = lm(Filtered_alphaDiv_bact_pielou ~ Category*Raw.or.Conventional, data=alpha_pielou)
hist(resid(anv7))
plot(predict(anv7), resid(anv7))
summary(anv7)
anova(anv7)


```


##ANOVA graphs

```{r 8, warning = FALSE, message=FALSE}
filtered_anv <- anv %>% 
  filter(!(interaction(Category, Raw.or.Conventional) %in% c(".0", ".1")))

filtered_anv$interaction_group <- interaction(filtered_anv$Category, filtered_anv$Raw.or.Conventional)

grouped_data <- filtered_anv %>%
  group_by(Category, Raw.or.Conventional) %>%
  summarise(mean_response = mean(AMRgenes..10, na.rm = TRUE),
            se_response = sd(AMRgenes..10, na.rm = TRUE) / sqrt(n()),
            .groups = "drop")

p <- ggplot(filtered_anv, aes(x = Category, y = AMRgenes..10, fill = Raw.or.Conventional)) +
  geom_boxplot(position = position_dodge(0.8)) +
  stat_summary(fun = mean, geom = "point", shape = 23, size = 2, position = position_dodge(0.8)) +
  labs(title = "Boxplot of AMR genes by Category and Raw or Conventional",
       x = "Category",
       y = "AMR Gene Count") +
  theme_minimal() +
  scale_fill_manual(values = c("#003F7D", "#FF8E00"), 
                    labels = c("Conventional", "Raw")) +
  guides(fill = guide_legend(title = "Processing Method"))

ggsave("ANOVA.png", plot = p, width = 12, height = 8, dpi = 300)

png("interaction_plot.png", width=1000, height=500)
interaction.plot(x.factor = anv$Category,
                 trace.factor = anv$Raw.or.Conventional,
                 response = anv$AMRgenes..10,
                 xlab = "Protein Category",
                 ylab = "Mean AMR Gene Count",
                 legend = TRUE, pch=c(1,19), col = c("#003F7D", "#FF8E00"),
                 trace.label = "Raw or Conventional",
                 type = "b")
dev.off()
```


```{r 7}

print(tukey.result)

tukey.data <- tidy(tukey.result)

# Split the term column into two new columns
tukey.data <- tukey.data %>%
  separate(term, into = c("Category", "Raw_or_Conventional"), sep = ":")

plot(tukey.result)

```

## Carbapenem

```{r 6}
carb <- file %>%
  select(Short.ID.with.zeros, Short.ID.without.zeros, Food.texture, Raw.or.Conventional, Carbapenem_genes) %>%
  na.omit()

table <- table(carb$Carbapenem_genes, carb$Raw.or.Conventional)
table

chisq.test(table)


```

## pie chart

```{r 3, warning=FALSE, message=FALSE}
file <- read.csv("092523_master clean cat food data compiled.csv") %>%
  select(Raw.or.Conventional, Prim.protein.Detected, 
         Category, cultured.bacteria.binary) %>%
  mutate(Prim.protein.Detected = toTitleCase(Prim.protein.Detected)) %>%
  na.omit()

count <- file %>%
  group_by(Category) %>%
  summarise(Count = n())

file$group <- with(file, paste(Category, cultured.bacteria.binary, sep = "_"))

# Calculate proportions for the pie chart
data_summary <- aggregate(cbind(freq = cultured.bacteria.binary) ~ group, file, length)
data_summary$ypos <- cumsum(data_summary$freq) - (0.5 * data_summary$freq) # For label positioning

pie_colors <- c("Aquatic_1" = "#1b9e77", "Aquatic_0" = "#66c2a5",
               "Avian_1" = "#d95f02", "Avian_0" = "#fc8d62",
               "Mammal_1" = "#7570b3", "Mammal_0" = "#9e9ac8")

#pie chart
pie_bacteria <- ggplot(data_summary, aes(x = "", y = freq, fill = group)) +
  geom_bar(width = 1, stat = "identity", color = "white") +
  scale_fill_manual(values = pie_colors) +
  coord_polar("y", start = 0) +
  theme_void() +
  labs(fill = "Group", title = "Pie Chart of identified bacteria isolates among protein sources")


ggsave("pie_bacteria.png", plot = pie_bacteria, width = 8, height = 8, dpi = 300)

#avian has 1 conventional, others are all from raw samples

```

## Heatmap Reorder columns

```{r 1}
file <- read.csv("cat_food_combined_data.csv", check.names = F)

static_columns <- c("Region", "Class", "Subclass")
dynamic_columns <- setdiff(names(file), static_columns)

initials <- gsub("([A-Za-z]+)[0-9]+", "\\1", dynamic_columns)
numbers <- as.numeric(gsub("[A-Za-z]+([0-9]+)", "\\1", dynamic_columns))

sorting_df <- data.frame(dynamic_columns, initials, numbers)

sorted_df <- sorting_df[order(sorting_df$initials, sorting_df$numbers),]

final_column_order <- c(static_columns, sorted_df$dynamic_columns)
sorted_data <- file[, final_column_order]

write.csv(sorted_data, "data_with_annotations.csv", row.names = F)
```

## Raw vs Conventional

```{r 2}
meta <- read.csv("raw_conventional.csv") %>%
  na.omit()

data_with_anno <- read.csv("data_with_annotations.csv", check.names = F)

data_with_anno[setdiff(names(data_with_anno), static_columns)] <- 
    as.numeric(data_with_anno[setdiff(names(data_with_anno), static_columns)] > 0)

binary_mat <- as.matrix(meta[, 2])
rownames(binary_mat) <- meta$Short.ID.without.zeros

binary_mat <- t(binary_mat)

mat <- as.matrix(data_with_anno[, -c(1, 2, 3)])

rownames(mat) <- data_with_anno$Region

conditional_addition <- function(mat, binary_mat){
  # Ensure dimensions are compatible
  if (ncol(mat) != length(binary_mat)) {
    stop("Dimensions of matrices are incompatible.")
  }
  
  # Create a copy of the original matrix
  result_mat <- mat
  
  # Apply the conditional operation
  for(j in 1:ncol(result_mat)){
    
    # If the corresponding value in binary_mat is 1
    if(binary_mat[j] == 1){
      
      # Only add 1 to positive values in that column of result_mat
      result_mat[result_mat[,j] > 0, j] <- result_mat[result_mat[,j] > 0, j] + 1
      
    }
    
  }
  
  return(result_mat)
}


new_mat <- conditional_addition(mat, binary_mat)

col_fun <- c("0" = "white","1" = "#003F7D", "2" = "#FF8E00")

column_categories <- c("C", "FD", "FR", "K")

class_info <- factor(data_with_anno$Class, 
                     levels = names(sort(table(data_with_anno$Class), 
                                         decreasing = TRUE)))

unique_classes <- unique(class_info)
unique_classes
class_color <- createPalette(34, c("#010101", "#ff0000"), M=1000)
class_color_mapping <- setNames(class_color, unique_classes)

groups_alt <- gsub("([A-Za-z]+)[0-9]+", "\\1", colnames(new_mat))

png("cat_food_heatmap.png", width = 4000, height = 3000, res = 200)
Heatmap(new_mat, name = "AMR", col = col_fun,
        column_title = "Sample ID",
        row_title = "AMR Gene",
        heatmap_legend_param = list(title = "Sample Type", 
                                    labels = c("Conventional", "Raw"), 
                                    at = c(1, 2)),
        right_annotation = rowAnnotation(Class = class_info, col = list(Class = class_color_mapping)),
        cluster_rows = FALSE, 
        cluster_columns = FALSE,
        show_row_names = F, 
        row_split = class_info, column_split = groups_alt,
        border = T)
dev.off()

```

## Citations

```{r citations}
cite_packages(out.dir = getwd())
```


