---
title: "Stats 9-12"
author: "Tina"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(tidyverse)
library(tools)
library(reshape2)
library(ggpubr)
library(stargazer)
library(grateful)
library(broom)
library(multcompView)
```

## Normality

```{r 1}
file <- read.csv("092523_master clean cat food data compiled.csv")

cultured_bacteria <- file %>%
  select(Short.ID.with.zeros, Short.ID.without.zeros, Food.texture, Raw.or.Conventional, cultured.bacteria, cultured.bacteria.binary, Category) %>%
  na.omit()

shapiro.test(cultured_bacteria$cultured.bacteria)

p <- ggplot(data = cultured_bacteria, aes(x = cultured.bacteria)) +
  geom_histogram(bins = 30, color = "black", fill = "lightblue") +
  theme_minimal() +
  labs(title = "Distribution of Cultured Bacteria",
       x = "# of Cultured Bacteria", y = "Count")

p

ggsave("cultured bacteria distribution.png", plot = p, width = 6, height = 4, dpi = 300)

AMR <- file %>%
  select(Short.ID.with.zeros, Short.ID.without.zeros, Raw.or.Conventional, AMRgenes..10) %>%
  na.omit()

normality <- ggplot(AMR, aes(x = AMRgenes..10)) +
  geom_histogram(bins = 30, color = "black", fill = "lightblue") +
  theme_minimal() +
  labs(title = "Distribution of AMR Genes",
       x = "# of AMR Genes", y = "Count")

normality

shapiro.test(AMR$AMRgenes..10)

ggsave("AMR distribution.png", plot = normality, width = 6, height = 4, dpi = 300)

```

## Wilcoxon rank-sum test

```{r 2}
#cultured bacteria
group_raw <- cultured_bacteria %>% 
  filter(Raw.or.Conventional == 1) %>% 
  pull(cultured.bacteria)

group_conventional <- cultured_bacteria %>% 
  filter(Raw.or.Conventional == 0) %>% 
  pull(cultured.bacteria)

grouped_data <- tibble(Raw.or.Conventional = 
                         c(rep("Raw", length(group_raw)),
                           rep("Conventional", length(group_conventional))),
                       cultured.bacteria = c(group_raw, group_conventional))

#filter(cultured.bacteria != 0) -- filtering out 0s

#side-by-side
side_by_side <- ggplot(grouped_data, 
                       aes(x = cultured.bacteria, fill = Raw.or.Conventional)) +
  geom_histogram(position = "dodge", binwidth = 0.5, alpha = 0.7) +
  labs(y = "Count", x = "# of Cultured Bacteria in Sample", fill = "Type") +
  scale_fill_manual(values = c("Raw" = "#FF8E00", "Conventional" = "#003F7D")) +
  theme_bw()

ggsave("Cultured_bacteria.png", plot = side_by_side, width = 6, height = 4, dpi = 300)

#if non-parametric
wilcox_test_result <- wilcox.test(group_raw, group_conventional)
print(wilcox_test_result)

#chi-square
test <- table(cultured_bacteria$Raw.or.Conventional, cultured_bacteria$cultured.bacteria.binary)
test

result <- chisq.test(test)
result

chisq.test(test)$expected

protein <- table(cultured_bacteria$Category, cultured_bacteria$cultured.bacteria.binary)
protein

chisq.test(protein)

texture <- table(cultured_bacteria$Food.texture, cultured_bacteria$cultured.bacteria.binary)
texture

chisq.test(texture)

```

## Cperf, Sal, Klebsiella

```{r 3}
#Cperf
species <- file %>%
  select(Short.ID.with.zeros, Short.ID.without.zeros, Raw.or.Conventional, Cperf, Salmonella, Klebsiella) %>%
  na.omit()

Cperf <- table(species$Cperf, species$Raw.or.Conventional)

result <- chisq.test(Cperf)
result

#Salmonella
Sal <- table(species$Salmonella, species$Raw.or.Conventional)
Sal

result <- chisq.test(Sal)
result

#Klebsiella
Kle <- table(species$Klebsiella, species$Raw.or.Conventional)

result <- chisq.test(Kle)
result

```

## AMR

```{r 4}
group_raw_AMR <- AMR %>% 
  filter(Raw.or.Conventional == 1) %>% 
  pull(AMRgenes..10)

group_conventional_AMR <- AMR %>% 
  filter(Raw.or.Conventional == 0) %>% 
  pull(AMRgenes..10)

AMR_wilcox_test_result <- wilcox.test(group_raw_AMR, group_conventional_AMR)
print(AMR_wilcox_test_result)

```

## Two-way ANOVA

```{r 5, warning = FALSE, message=FALSE}
anv <- file %>%
  select(Short.ID.with.zeros, Short.ID.without.zeros, Food.texture,
         Raw.or.Conventional, cultured.bacteria, 
         Prim.protein.Detected, Category, AMRgenes..10) %>%
  na.omit()

anv2 = lm(cultured.bacteria ~ Category*Raw.or.Conventional, data=anv)
hist(resid(anv2))
plot(predict(anv2), resid(anv2))
summary(anv2)
anova(anv2)

anv3 = lm(AMRgenes..10 ~ Category*Raw.or.Conventional, data=anv)
hist(resid(anv3))
plot(predict(anv3), resid(anv3))
summary(anv3)
anova(anv3)

anv$Category <- as.factor(anv$Category)
anv$Raw.or.Conventional <- as.factor(anv$Raw.or.Conventional)

anv3.aov <- aov(AMRgenes..10 ~ Category * Raw.or.Conventional, data=anv)
tukey.result <- TukeyHSD(anv3.aov, which = 'Category:Raw.or.Conventional')
print(tukey.result)

anv4 = lm(AMRgenes..10 ~ Food.texture * Raw.or.Conventional, data = anv)
hist(resid(anv4))
plot(predict(anv4), resid(anv4))
summary(anv4)
anova(anv4)

```

##Alpha and beta diversity

```{r 9}
diversity <- file %>%
  select(Short.ID.with.zeros, Short.ID.without.zeros, Food.texture,
         Raw.or.Conventional, Category, alphaDiv_bact..Faith.PD., alphaDiv_bact..pielou., betaDiv_bact)

alpha_Faith <- diversity %>%
  select(Short.ID.with.zeros, Short.ID.without.zeros, Food.texture,
         Raw.or.Conventional, Category, alphaDiv_bact..Faith.PD.) %>%
  na.omit()

alpha_pielou <- diversity %>%
  select(Short.ID.with.zeros, Short.ID.without.zeros, Food.texture,
         Raw.or.Conventional, Category, alphaDiv_bact..pielou.) %>%
  na.omit()

beta <- diversity %>%
  select(Short.ID.with.zeros, Short.ID.without.zeros, Food.texture,
         Raw.or.Conventional, Category, betaDiv_bact) %>%
  na.omit()

ggplot(alpha_Faith, aes(x = Category, y = alphaDiv_bact..Faith.PD., fill = Category)) +
  geom_boxplot()

anv5 = lm(alphaDiv_bact..Faith.PD. ~ Category*Raw.or.Conventional, data=alpha_Faith)
hist(resid(anv5))
plot(predict(anv5), resid(anv5))
summary(anv5)
anova(anv5)

anv6 = lm(betaDiv_bact ~ Category*Raw.or.Conventional, data=beta)
hist(resid(anv6))
plot(predict(anv6), resid(anv6))
summary(anv6)
anova(anv6)

anv7 = lm(alphaDiv_bact..pielou. ~ Category*Raw.or.Conventional, data=alpha_pielou)
hist(resid(anv7))
plot(predict(anv7), resid(anv7))
summary(anv7)
anova(anv7)


```

## Tables

```{r 7}
stargazer(anv3, type="text", report=('vc*t'), 
          title="Regression Results", intercept.bottom=FALSE,
          single.row=TRUE, align = TRUE, out = "output.txt",
          digits = 2, dep.var.labels="AMR Gene Count")

anova_table <- anova(anv3.aov)
stargazer(anova_table, type="text", digits = 2,
          title="ANOVA Results for AMR Gene Count Predicted by Protein Category, Processing Method, and Their Interaction", 
          align = TRUE, out = "anova_output.txt")
```

##ANOVA graphs

```{r 8, warning = FALSE, message=FALSE}
filtered_anv <- anv %>% 
  filter(!(interaction(Category, Raw.or.Conventional) %in% c(".0", ".1")))

filtered_anv$interaction_group <- interaction(filtered_anv$Category, filtered_anv$Raw.or.Conventional)

grouped_data <- filtered_anv %>%
  group_by(Category, Raw.or.Conventional) %>%
  summarise(mean_response = mean(AMRgenes..10, na.rm = TRUE),
            se_response = sd(AMRgenes..10, na.rm = TRUE) / sqrt(n()),
            .groups = "drop")

ggplot(filtered_anv, aes(x = Category, y = AMRgenes..10, 
                              fill = Raw.or.Conventional)) +
  geom_boxplot(position = position_dodge(0.8)) +
  stat_summary(fun = mean, geom = "point", shape = 23, size = 2, position = position_dodge(0.8)) +
  labs(title = "Boxplot of AMR genes by Category and Raw or Conventional",
       x = "Category",
       y = "AMR Gene Count") +
  theme_minimal() +
  scale_fill_manual(values = c("#003F7D", "#FF8E00"), 
                    labels = c("Conventional", "Raw")) +
  guides(fill = guide_legend(title = "Processing Method"))

ggsave("ANOVA.png", plot = p, width = 12, height = 8, dpi = 300)

png("interaction_plot.png", width=1000, height=500)
interaction.plot(x.factor = anv$Category,
                 trace.factor = anv$Raw.or.Conventional,
                 response = anv$AMRgenes..10,
                 xlab = "Protein Category",
                 ylab = "Mean AMR Gene Count",
                 legend = TRUE, pch=c(1,19), col = c("#003F7D", "#FF8E00"),
                 trace.label = "Raw or Conventional",
                 type = "b")
dev.off()
```


```{r 7}
anv3.aov <- aov(AMRgenes..10 ~ Category * Raw.or.Conventional, data=anv)
tukey.result <- TukeyHSD(anv3.aov, which = 'Category:Raw.or.Conventional')
print(tukey.result)

tukey.data <- tidy(tukey.result)

# Split the term column into two new columns
tukey.data <- tukey.data %>%
  separate(term, into = c("Category", "Raw_or_Conventional"), sep = ":")

plot(tukey.result)

```

## Carbapenem

```{r 6}
carb <- file %>%
  select(Short.ID.with.zeros, Short.ID.without.zeros, Food.texture, Raw.or.Conventional, Category, Carbapenem_genes) %>%
  na.omit()

table <- table(carb$Carbapenem_genes, carb$Raw.or.Conventional)
table

chisq.test(table)


```

## Citations

```{r citations}
cite_packages(out.dir = getwd())

```
