---
title: "Cat food stats analysis"
author: "Tina"
date: "2023-08-28"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(tidyverse)
library(tools)
library(reshape2)
```

## Normality

```{r 1}
file <- read.csv("081023_master clean cat food data compiled.csv")

cultured_bacteria <- file %>%
  select(Short.ID.with.zeros, Short.ID.without.zeros, Food.texture, Raw.or.Conventional, cultured.bacteria, cultured.bacteria.binary, Category) %>%
  na.omit()

shapiro.test(cultured_bacteria$cultured.bacteria)

p <- ggplot(data = cultured_bacteria, aes(x = cultured.bacteria)) +
  geom_histogram(bins = 30, color = "black", fill = "lightblue") +
  theme_minimal() +
  labs(title = "Distribution of Cultured Bacteria",
       x = "# of Cultured Bacteria", y = "Count")

p

ggsave("cultured bacteria distribution.png", plot = p, width = 6, height = 4, dpi = 300)

AMR <- file %>%
  select(Short.ID.with.zeros, Short.ID.without.zeros, Raw.or.Conventional, AMRgenes..10) %>%
  na.omit()

normality <- ggplot(AMR, aes(x = AMRgenes..10)) +
  geom_histogram(bins = 30, color = "black", fill = "lightblue") +
  theme_minimal() +
  labs(title = "Distribution of AMR Genes",
       x = "# of AMR Genes", y = "Count")

normality

shapiro.test(AMR$AMRgenes..10)

ggsave("AMR distribution.png", plot = normality, width = 6, height = 4, dpi = 300)

```

## T-test

```{r 2}
#cultured bacteria
group_raw <- cultured_bacteria %>% 
  filter(Raw.or.Conventional == 1) %>% 
  pull(cultured.bacteria)

group_conventional <- cultured_bacteria %>% 
  filter(Raw.or.Conventional == 0) %>% 
  pull(cultured.bacteria)

grouped_data <- tibble(Raw.or.Conventional = 
                         c(rep("Raw", length(group_raw)),
                           rep("Conventional", length(group_conventional))),
                       cultured.bacteria = c(group_raw, group_conventional))

#filter(cultured.bacteria != 0) -- filtering out 0s

#side-by-side
ggplot(grouped_data, aes(x = cultured.bacteria, fill = Raw.or.Conventional)) +
  geom_histogram(position = "dodge", bins = 30, alpha = 0.7) +
  labs(y = "Count", x = "# of Cultured Bacteria in Sample", fill = "Type") +
  theme_minimal()

#if non-parametric
wilcox_test_result <- wilcox.test(group_raw, group_conventional)
print(wilcox_test_result)

#chi-square
test <- table(cultured_bacteria$Raw.or.Conventional, cultured_bacteria$cultured.bacteria.binary)
test

result <- chisq.test(test)
result

chisq.test(test)$expected

protein <- table(cultured_bacteria$Category, cultured_bacteria$cultured.bacteria.binary)
protein

chisq.test(protein)

texture <- table(cultured_bacteria$Food.texture, cultured_bacteria$cultured.bacteria.binary)
texture

chisq.test(texture)

```

## Cperf, Sal, Klebsiella

```{r 3}
#Cperf
species <- file %>%
  select(Short.ID.with.zeros, Short.ID.without.zeros, Raw.or.Conventional, Cperf, Salmonella, Klebsiella) %>%
  na.omit()

Cperf <- table(species$Cperf, species$Raw.or.Conventional)

result <- chisq.test(Cperf)
result

#Salmonella
Sal <- table(species$Salmonella, species$Raw.or.Conventional)

result <- chisq.test(Sal)
result

#Klebsiella
Kle <- table(species$Klebsiella, species$Raw.or.Conventional)

result <- chisq.test(Kle)
result

```
## AMR
```{r 4}
group_raw_AMR <- AMR %>% 
  filter(Raw.or.Conventional == 1) %>% 
  pull(AMRgenes..10)

group_conventional_AMR <- AMR %>% 
  filter(Raw.or.Conventional == 0) %>% 
  pull(AMRgenes..10)

AMR_wilcox_test_result <- wilcox.test(group_raw_AMR, group_conventional_AMR)
print(AMR_wilcox_test_result)

```

## Two-way ANOVA
```{r 5}
anv <- file %>%
  select(Short.ID.with.zeros, Short.ID.without.zeros, Food.texture,
         Raw.or.Conventional, cultured.bacteria, 
         Prim.protein.Detected, Category, AMRgenes..10) %>%
  na.omit()

anv2 = lm(cultured.bacteria ~ Category*Raw.or.Conventional, data=anv)
hist(resid(anv2))
plot(predict(anv2), resid(anv2))
summary(anv2)
anova(anv2)

anv3 = lm(AMRgenes..10 ~ Category*Raw.or.Conventional, data=anv)
hist(resid(anv3))
plot(predict(anv3), resid(anv3))
summary(anv3)
anova(anv3)

boxplot(AMRgenes..10 ~ Category * Raw.or.Conventional, 
        data=anv, cex.axis=0.6)

interaction.plot(x.factor = anv$Category,
                 trace.factor = anv$Raw.or.Conventional,
                 response = anv$AMRgenes..10,
                 xlab = "Category",
                 ylab = "AMR",
                 legend = TRUE,
                 trace.label = "Raw or Conventional")

anv$Category <- as.factor(anv$Category)
anv$Raw.or.Conventional <- as.factor(anv$Raw.or.Conventional)

anv3.aov <- aov(AMRgenes..10 ~ Category * Raw.or.Conventional, data=anv)
tukey.result <- TukeyHSD(anv3.aov)
print(tukey.result)

anv4 = lm(AMRgenes..10 ~ Food.texture * Raw.or.Conventional, data = anv)
hist(resid(anv4))
plot(predict(anv4), resid(anv4))
summary(anv4)
anova(anv4)

```

## Carbapenem
```{r 6}
carb <- file %>%
  select(Short.ID.with.zeros, Short.ID.without.zeros, Food.texture, Raw.or.Conventional, Category, Carbapenem_genes) %>%
  na.omit()

table <- table(carb$Carbapenem_genes, carb$Raw.or.Conventional)
table

chisq.test(table)

citation()
version$version.string

```









