---
title: "cat food presentation"
author: "Tina, Marie, Kelly"
date: "2023-07-27"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(tidyverse)
library(tools)
library(EnvStats)
```

## import files

```{r 1}
file <- read.csv("092523_master clean cat food data compiled.csv") %>%
  select(Raw.or.Conventional, Prim.protein.Detected, 
         Category, cultured.bacteria) %>%
  mutate(Prim.protein.Detected = toTitleCase(Prim.protein.Detected)) %>%
  na.omit()

df <- file %>%
  group_by(Prim.protein.Detected) %>%
  summarize(n = n(), mean_value = mean(cultured.bacteria)) %>%
  na.omit()
  
df

df_means <- file %>%
  group_by(Category) %>%
  summarize(mean_value = mean(cultured.bacteria))

df_means
```

## bar graph

```{r 2}
bar_bacteria <- ggplot(df, mapping = aes(x=reorder(Prim.protein.Detected, +mean_value), y=mean_value)) +
  geom_col(fill= "cornflowerblue") +
  labs(title = "Mean of Bacteria Species by Primary Protein Source",
       x = "Primary Protein Source", y = "Mean") +
  theme_minimal() +
  geom_text(aes(label = round(mean_value, 2)), vjust = -0.5)

ggsave("bar_bacteria.png", plot = bar_bacteria, width = 6, height = 6, dpi = 300)

```

## stats

```{r 4}
#ANOVA
res.aov <- aov(cultured.bacteria ~ Category, data = file)
summary_res <- summary(res.aov)
summary_res
aov_p_value <- summary_res[[1]]["Category", "Pr(>F)"]
aov_p_value
         
#Tukey HSD
TukeyHSD(res.aov, conf.level=.95)

```

## box plot

```{r 3, warning=FALSE, message=FALSE}
box_bacteria <- ggplot(file, mapping = aes(x=Category, y=cultured.bacteria, fill = Category)) +
  geom_boxplot(notch = TRUE) +
  stat_n_text() +
  stat_summary(fun = mean, geom = "crossbar", width = 0.7, color = "yellow", fatten = 2) +
  annotate("text", x = "Mammal", y = max(file$cultured.bacteria) + 1, label = paste("ANOVA p-value =", round(aov_p_value, 4))) +
  theme_minimal() +
  geom_text(data = df_means, aes(x = Category, y = mean_value, label = round(mean_value, 2)), nudge_y = 0.55) +
  theme_minimal() +
  labs(title = "Bacterial Load by Protein Source", y = "Number of Bacterial Species") +
  theme(legend.position = "none",
        axis.title.x = element_blank(),
        axis.ticks.x = element_blank())

ggsave("box_bacteria.png", plot = box_bacteria, width = 8, height = 8, dpi = 300)

```

## AMR
```{r 5, warning=FALSE, message=FALSE}
AMR <- read.csv("092523_master clean cat food data compiled.csv") %>%
  select(Short.ID.with.zeros, Short.ID.without.zeros,
         Raw.or.Conventional, Prim.protein.Detected, Category, AMRgenes..10) %>%
  na.omit() %>%
  mutate(Prim.protein.Detected = toTitleCase(Prim.protein.Detected)) %>%
  group_by(Prim.protein.Detected) %>%
  summarize(n = n(), mean_value = mean(AMRgenes..10))

bar_AMR <- ggplot(AMR, mapping = aes(x=reorder(Prim.protein.Detected, +mean_value), y = mean_value)) +
  geom_col(fill= "cornflowerblue") +
  labs(title = "Mean of AMR Gene Count by Primary Protein Source",
       x = "Primary Protein Source", y = "Mean") +
  theme_minimal() +
  geom_text(aes(label = round(mean_value, 2)), vjust = -0.5)

ggsave("bar_AMR.png", plot = bar_AMR, width = 6, height = 6, dpi = 300)

AMR_df <- read.csv("092523_master clean cat food data compiled.csv") %>%
  select(Prim.protein.Detected, Category, AMRgenes..10) %>%
  mutate(Prim.protein.Detected = toTitleCase(Prim.protein.Detected)) %>%
  group_by(Prim.protein.Detected) %>%
  na.omit()

AMR_df <- AMR_df[-97, ]

AMR_df_means <- read.csv("092523_master clean cat food data compiled.csv") %>%
  select(Category, AMRgenes..10) %>%
  group_by(Category) %>%
  summarize(n = n(), mean_value = mean(AMRgenes..10)) %>%
  na.omit()

#ANOVA
AMR_aov <- aov(AMRgenes..10 ~ Category, data = AMR_df)
summary_AMR <- summary(AMR_aov)
summary_AMR
AMR_p_value <- summary_AMR[[1]]["Category", "Pr(>F)"]
AMR_p_value

#Tukey HSD
TukeyHSD(AMR_aov, conf.level=.95)

box_AMR <- ggplot(AMR_df, mapping = aes(x = Category, y = AMRgenes..10, fill = Category)) +
  geom_boxplot(notch = TRUE) +
  stat_n_text() +
  stat_summary(fun = mean, geom = "crossbar", width = 0.7, color = "yellow", fatten = 2) +
  annotate("text", x = "Mammal", y = max(AMR_df$AMRgenes..10)-4, label = paste("ANOVA p-value =", round(AMR_p_value, 4))) +
  theme_minimal() +
  geom_text(data = AMR_df_means, aes(x = Category, y = mean_value, label = round(mean_value, 2)), nudge_y = 0.55) +
  theme_minimal() +
  labs(title = "AMR Gene Count by Protein Source", y = "AMR Gene Count") +
  theme(legend.position = "none",
        axis.title.x = element_blank(),
        axis.ticks.x = element_blank())

ggsave("box_AMR.png", plot = box_AMR, width = 8, height = 8, dpi = 300)

```








